### ISSUE TITLE
aisleriot.js fails to open start.scm due to CORS problem

### ISSUE THREAD

**Issue by k3zaa** [ecrips/webaisleriot#1]
Very cool piece of code for the Guile files in aisleriot!!! It used to work fine for me now fails after I upgraded Fedora 29 to 30.

Here are the error messages from Firefox Debug Web Console running on Fedora 30 Xfce:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/

**Cross-Origin Request Blocked**: **The Same Origin Policy** disallows reading the remote resource at file:///home/bill/Desktop/ar-js-orig/start.scm. (Reason: CORS request not http)

The failing code is:
function fetchFile(filename)
{
	var request = new XMLHttpRequest();
	request.open("GET", name, false);
	request.overrideMimeType("text/plain");
	request.send(null);
	return request.responseText;
}

**Comment by k3zaa** [comment]
Turns out the problem is with Firefox 68. Firefox 67 was ok until the security hole was closed. The security violation also occurs in Chrome on Fedora and Windows. Interesting that microsoft's edge on windows 10 lets the code run ok.

**Comment by k3zaa** [comment]
Just setup Apache web server and the code runs just fine when served up by Apache.

**Comment by ecrips** [comment]
Yes, Firefox seems to have moved in line with Chrome and blocked accesses from file:// URLs: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

These days most browsers require you to load web pages from http(s) for all the features to be enabled. I do host webaisleriot here in case that's helpful: https://ecrips.co.uk/aisleriot/aisleriot.html

Btw the synchronous XMLHttpRequest is a different issue - but so far I don't think any browser has actually disabled it yet. Unfortunately it's not a particularly simple fix as the underlying scheme code expects the load to be synchronous.
