### ISSUE TITLE
Question: how to get you a copy of aisleriot.js with my updates

### ISSUE THREAD

**Issue by k3zaa** [ecrips/webaisleriot#2]
I forked webaisleriot and have made some updates to aisleriot.js to help with debugging my own Guile code etc.
Added bounds checking to cdr and list-tail.
Added new functions for list-head, object->string and newline.
Added block comments for #!....!# like Guile has.
I've attached the file too.
Bill, K3ZAA, Columbus OH

[aisleriot.js.txt](https://github.com/ecrips/webaisleriot/files/3473228/aisleriot.js.txt)

**Comment by ecrips** [comment]
I've create a pull request and fixed up some style issues, and also changed the behaviour of comments slightly. In particular something like:

```
(my-func; comment
tion)
```

shouldn't be parsed as "(my-function)" but as two symbols "(my-func tion)" hence pretending the comment is a space. There also seemed to be a off-by-one error in skipping characters at the end of the comment. Let me know if you're happy with the changes and I'll merge the pull request.

In future you should be able to create a pull request directly into my repository which saves some manual work creating the commit here.
